language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: ozosMBWHNbAPnKtoKy/GbN7xYwkttGrL0uBdjeT5hbt5UjA+zKPshIva2HA0st0ugkyL9mZYxeyCVd4vYKMcRMJv6kn1V+gda7sIomAZPEgRWpMEyXIGI5wt/Egy80mJH05RJMMQZ7P2j9h1kibg24+KJ4f7MDiAw+Qvo3tbuGCrupZtqACD4bqzwge8U1trOM3yvaStGkfPgFXCbB5w8WoKE0G2sRV25nsfp/i12gjziZMpAy9onsSZB7U/axLw+q2c1CxzqgtjaUsz9iRSj8+f2i60pOL3L+qJItbrSzX1aFsTWhOlfEtp6fNtSumMLSDpdi1B0fVDzSMOMZTFwzYl4+C/sLujNgCIdatDnGMuLV9pnbuxkjyC575iQoV1WvRr+4TsawcisUa7Heg6UBcOoEyN4r7NI9Oyy2HPSvGDYMP6UlYCn3XLIp6bISC9GvEZV97vJTFl0ZaZwmtZK9R1VvSV4Fm/EMJJRw+G9DIiWXI2RKZrNiHi0y+Mwf3yZdAiYEpW6oHwvANRX7zyQ8lUgVNV9DxgwOkWUXoJLzQZ7sEbBfPZrlbUDASceEbsP2iTdx8BCRNh12Pf4A26zLKR+17q6KAXDbQnJEWcf7DRGd8OIVSqD41424J/vq0AOVv8bH44Rc+j3FpcE3F+i27Ezq0YzTal0y8+r5EdHAM=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: cSjZ9V7PDWqGp2CGPTsxB0A6I1qClcus7zTa1uNN6Is/jvjLNRL9ahSBxIxcrZRauBKoOCq1rwFmVUkMOz8Oca3bXKCS+k+M1U4CK/QFCNLVAVJbYinQ2OCgP2cmzLGlU9uQz/ku2GHEPVnvrLYJvse6H016QFNj+UtZ3jI3uKHf9xTKxam3AcVL7vriMgsMHRmnX6l6FQ8YL+XQZyreJ6BJDVhSic7adcC2LLK6KcRY/ETkO1Dg8am0efq3KG6yNgMduOqRCS5hGh7rq/83iXkGTT0EJEvjm+msJOlxHhNo6U5PEzVIc7KnxFcQN+9demyL3PYEWMIJv55DAPyxPoclQiGhIedINJ5iNtcpPstOCiqGxcr/sD6eKWN+s6mPEVappZU0IfOGN72wrCwInUke8is9gQKSR13u0jXPj1ra8GOEH1lfdLUlbj/5G2tyCqUgP0pYfjtjyA6Ww9FtzMlk4u/3qQtuH59bL8/Oec7CXshcbSwuOJRH+FcCBVZctqjSYFqN2E5PHKPxhRSj8nVV6xEo0im0RvPGFdygaA2UC491uV4A8vl1QYY6N9FjK7jZy6TaxKrgFBGo/i5CqAoXxVlUU6VxqzTE4v/wVM0QicO7wcKE8jKl/VGOse756kneyXE9Nasy4ZfzfNJKAF4DhIiVIrPUb72BkwZzwNc=
  - secure: jofuxi9nqx5S0GQ/KRkWIv1AHhBC3lo571I04ZEIfw54rEZf4iIom61JCnHDibxVOVwl+YdHzw/pC7292aXJxDrX2GfxsftrSnpHt1zvssGARJCfD4nf10UE6Z9WSqhpW4k/boAARP6i/Tbr7CX5eg82TJN6s1iYwtJZJMrQ+DHZhL3/g7vc0RHNpDoPEsLo0wLxofCaYcITILMiHr35CJRAt3LAtCyw09MXtB5SmYktMBzw6hDRP/I/7MTyuJ7xTRBI3bGa+URN7eMyvtWkTD2OEv9nkhjAoqfCarZR+BkzEdX73zKp8wotYyk74RkLLUZjMqGVsboxEe5oRqIyETcl7GdeWUeqbAPxUp8NtP7L6a/EX6KgnUkIIqW6sp/6XPg40hcqR4jkOvz1WyYEU2wpp91dNBGntjcxFWJmm+L/zgrrnn/E9wd7M6cb1XAK1t8zgF9uIKFLZv8VcvTfLegI92Grn799D5rWdLkoiXY0v14TrfdeYvVPDjcInnW3GjL/7ZJNw8a1fO8Vk9Pgwrtm/FodWZbjrv1bLP5Y6/6A4wFboS+QQTuBLL62GQkMwI1iniF9JUMaND9mkZDSu69GRwfeB2/4n9w4JimrgHTnsiN1QHNj4FuWbcK3hNCQiPGK/4xWE0+519UKqJr7cnDIjKp/Cj1WrYJFgyzs7PU=  
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-logstash:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
